### ISSUE TITLE
Not able to route request to remote service in multicluster

### ISSUE THREAD

**Issue by kpiyush17** [johscheuer/istio-playground#1]
Hi,

I am following your steps in doing transparent multicluster. I have two cluster one in EKS and one in AKS. I am trying to establish a failover from EKS to AKS. So far, I have configured all the necessary steps. I have a greeter service which calls a messenger service. 
I am able to see from the istio-proxy of greeter service in EKS that the request is going to the remote cluster AKS ingress-cluster by looking at the `upstream-host` field.
```
{
	"upstream_cluster": "outbound|3000||messenger.test.svc.cluster.local",
	"downstream_remote_address": "192.168.82.214:53514",
	"authority": "messenger.test.svc.cluster.local:3000",
	"path": "/",
	"protocol": "HTTP/1.1",
	"upstream_service_time": "-",
	"upstream_local_address": "-",
	"duration": "348",
	"upstream_transport_failure_reason": "-",
	"route_name": "default",
	"downstream_local_address": "10.100.161.225:3000",
	"user_agent": "-",
	"response_code": "503",
	"response_flags": "UH",
	"start_time": "2020-11-10T08:21:02.395Z",
	"method": "GET",
	"request_id": "c53e148d-0a72-97c6-9ea6-98716ed47319",
	"upstream_host": "<remote-cluster ingress gateway external ip>:15443",
	"x_forwarded_for": "-",
	"requested_server_name": "-",
	"bytes_received": "0",
	"istio_policy_status": "-",
	"bytes_sent": "19"
}
```
But in the logs, I am receiving a response code 503.

I checked in the AKS ingress gateway logs and from the logs I am able to deduce that request are coming to ingress but it is not going to the service.
Ingress logs:
```
{
	"upstream_transport_failure_reason": "-",
	"route_name": "-",
	"downstream_local_address": "10.244.1.3:15443",
	"user_agent": "-",
	"response_code": "0",
	"response_flags": "-",
	"start_time": "2020-11-10T08:21:02.687Z",
	"method": "-",
	"request_id": "-",
	"upstream_host": "10.244.1.170:3000",
	"x_forwarded_for": "-",
	"requested_server_name": "outbound_.3000_._.messenger.test.svc.cluster.local",
	"bytes_received": "2000",
	"istio_policy_status": "-",
	"bytes_sent": "3385",
	"upstream_cluster": "outbound_.3000_._.messenger.test.svc.cluster.local",
	"downstream_remote_address": "10.244.1.1:53092",
	"authority": "-",
	"path": "-",
	"protocol": "-",
	"upstream_service_time": "-",
	"upstream_local_address": "10.244.1.3:46484",
	"duration": "77"
}
```
Here, I am not able to figure out the issue as there is no error and the response code is 0.
Need some help in debugging the issue.

ServiceEntry in EKS:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: messenger
spec:
  hosts:
  - messenger.test.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 3000
    protocol: http
  resolution: STATIC
  endpoints:
  - address: <IP of AKS ingress>
    locality: uksouth/0
    ports:
      http: 15443
```

Thanks
